#!/bin/bash

cat <<"EOF"



  _________    ___.        .___                    .__                     
 /   _____/__ _\_ |__    __| _/____   _____ _____  |__| ____   ___________ 
 \_____  \|  |  \ __ \  / __ |/  _ \ /     \\__  \ |  |/    \_/ __ \_  __ \
 /        \  |  / \_\ \/ /_/ (  <_> )  Y Y  \/ __ \|  |   |  \  ___/|  | \/
/_______  /____/|___  /\____ |\____/|__|_|  (____  /__|___|  /\___  >__|   
        \/          \/      \/            \/     \/        \/     \/       

		    Automated Subdomain Gathering Tool
			  Developed By Momen Ali
			      The Cyber Guy

			 _           _        _ _ 
			(_)_ __  ___| |_ __ _| | |
			| | '_ \/ __| __/ _` | | |
			| | | | \__ \ || (_| | | |
			|_|_| |_|___/\__\__,_|_|_|
                                    

EOF

mkdir -p Tools

cd Tools
printf "\n\n\e[92m=============================================\e[0m"
printf "\n\n\e[92m           	Updating Repos               \e[0m"
printf "\n\n\e[92m=============================================\e[0m\n\n"

sudo apt update

printf "\n\n\e[92m=============================================\e[0m"
printf "\n\n\e[92m             Installing Git              \e[0m"
printf "\n\n\e[92m=============================================\e[0m\n\n"

sudo apt -y install git

printf "\n\n\e[92m=============================================\e[0m"
printf "\n\n\e[92m             Installing Python3              \e[0m"
printf "\n\n\e[92m=============================================\e[0m\n\n"

sudo apt -y install python3

printf "\n\n\e[92m=============================================\e[0m"
printf "\n\n\e[92m              Installing PIP3              \e[0m"
printf "\n\n\e[92m=============================================\e[0m\n\n"

sudo apt -y install python3-pip

printf "\n\n\e[92m=============================================\e[0m"
printf "\n\n\e[92m             Installing Python2              \e[0m"
printf "\n\n\e[92m=============================================\e[0m\n\n"

sudo apt -y install python2

printf "\n\n\e[92m=============================================\e[0m"
printf "\n\n\e[92m              Installing Golang              \e[0m"
printf "\n\n\e[92m=============================================\e[0m\n\n"

sudo apt -y install golang

printf "\n\n\e[92m=============================================\e[0m"
printf "\n\n\e[92m      Installing Addtional Packages           \e[0m"
printf "\n\n\e[92m=============================================\e[0m\n\n"

sudo apt -y install libcurl4-openssl-dev libxml2 libxml2-dev libxslt1-dev ruby-dev build-essential libgmp-dev zlib1g-dev build-essential libssl-dev libffi-dev python-dev libldns-dev jq ruby-full python3-setuptools python3-dnspython rename findutils

printf "\n\n\e[92m=============================================\e[0m"
printf "\n\n\e[92m           Sublist3r Installing              \e[0m"
printf "\n\n\e[92m=============================================\e[0m\n\n"

git clone https://github.com/aboul3la/Sublist3r.git

cd Sublist3r/

pip3 install -r requirements.txt

cd ../

printf "\n\n\e[92m=============================================\e[0m"
printf "\n\n\e[92m         Github-Search Installing              \e[0m"
printf "\n\n\e[92m=============================================\e[0m\n\n"

git clone https://github.com/gwen001/github-search.git

printf "\n\n\e[92m=============================================\e[0m"
printf "\n\n\e[92m             Knockpy Installing              \e[0m"
printf "\n\n\e[92m=============================================\e[0m\n\n"

git clone https://github.com/guelfoweb/knock.git

cd knock

sudo python3 setup.py install

cd ../

printf "\n\n\e[92m=============================================\e[0m"
printf "\n\n\e[92m             Aquatone Installing              \e[0m"
printf "\n\n\e[92m=============================================\e[0m\n\n"

go get github.com/michenriksen/aquatone

###########################################################################################################
# If Not Installed Do The Following Commands:
#
# wget https://github.com/michenriksen/aquatone/releases/download/v1.7.0/aquatone_linux_amd64_1.7.0.zip
# unzip aquatone_linux_amd64_1.7.0.zip
# sudo mv aquatone /usr/bin/
#
###########################################################################################################

printf "\n\n\e[92m=============================================\e[0m"
printf "\n\n\e[92m             Httpx Installing              \e[0m"
printf "\n\n\e[92m=============================================\e[0m\n\n"

GO111MODULE=on go get -v github.com/projectdiscovery/httpx/cmd/httpx

###########################################################################################################
# If Not Installed Do The Following Commands:
#
# wget https://github.com/projectdiscovery/httpx/releases/download/v1.1.0/httpx_1.1.0_linux_amd64.tar.gz
# tar -xvf httpx_1.1.0_linux_amd64.tar.gz
# sudo mv httpx /usr/bin
#
###########################################################################################################

printf "\n\n\e[92m=============================================\e[0m"
printf "\n\n\e[92m             Assetfinder Installing              \e[0m"
printf "\n\n\e[92m=============================================\e[0m\n\n"

go get -u github.com/tomnomnom/assetfinder

printf "\n\n\e[92m=============================================\e[0m"
printf "\n\n\e[92m             Subdfinder Installing              \e[0m"
printf "\n\n\e[92m=============================================\e[0m\n\n"

GO111MODULE=on go get -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder

###########################################################################################################
# If Not Installed Do The Following Commands:
#
# wget https://github.com/projectdiscovery/subfinder/releases/download/v2.4.8/subfinder_2.4.8_linux_amd64.tar.gz
# tar -xvf subfinder_2.4.8_linux_amd64.tar.gz
# sudo mv subfinder /usr/bin
#
###########################################################################################################

printf "\n\n\e[92m=============================================\e[0m"
printf "\n\n\e[92m           	Installing CRTSh               \e[0m"
printf "\n\n\e[92m=============================================\e[0m\n\n"

git clone https://github.com/YashGoti/crtsh.git

cd crtsh/

pip3 install -r requirements.txt

cd ../

printf "\n\n\e[92m=============================================\e[0m"
printf "\n\n\e[92m   Installing Additional Python Modules               \e[0m"
printf "\n\n\e[92m=============================================\e[0m\n\n"

pip3 install colored
pip3 install tldextract


printf "\n\n\e[92m=============================================\e[0m"
printf "\n\n\e[92m                 Happy Hacking               \e[0m"
printf "\n\n\e[92m                 Stay Secure ;)               \e[0m"
printf "\n\n\e[92m=============================================\e[0m\n\n"

printf "\n\n\e[96m===================================================================================\e[0m"
printf "\n\n\e[96m                              Attention Please                                     \e[0m"
printf "\n\n\e[96mIf There Any Tools Not Installed Please See The install Script Source              \e[0m"
printf "\n\n\e[96m===================================================================================\e[0m\n\n"
